# Generated by Django 3.0.8 on 2021-01-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_auto_20210107_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='voir',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
